pipeline {
    agent any

    stages {
        stage('BE Unit Tests') {
            steps {
              dir('bugtracker-backend') {
                go test -v ./...
              }
            }
        }
    }
}
