pipeline {
    agent any

    stages {
        stage('BE Unit Tests') {
            agent {
              docker {
                image 'snakee/golang-junit:1.21'
                reuseNode true
                args '--user root'
              }
            }
            steps {
              dir('bugtracker-backend') {
                sh 'go test -v ./... 2>&1 | go-junit-report > test-results.xml'
              }
            }
            post {
              always {
                junit 'bugtracker-backend/test-results.xml'
              }
            }
        }
        stage('FE Unit Tests') {
            agent {
              docker {
                image 'node:20-alpine'
                reuseNode true
                args '--user root'
              }
            }
            steps {
              dir('bugtracker-frontend') {
                sh '''
                  npm ci
                  npm test
                '''
              }
            }
            post {
              always {
                junit 'bugtracker-frontend/test-results.xml'
              }
            }
        }
    }
}
